# Site settings
title: "Rui Zhao - @renyuneyun"
description: >- # this means to ignore newlines until "baseurl:"
    Postdoc at Department of Computer Science, University of Oxford  <br />
    Data privacy; user empowerment; data-use policy
baseurl: ""
url: "https://me.ryey.icu" # the base hostname & protocol for your site, e.g. http://example.com
repository: renyuneyun/renyuneyun.github.io


# Build settings
markdown: kramdown
remote_theme: YoussefRaafatNasry/portfolYOU@v2.3.0
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Rui Zhao (renyuneyun)
  image    : https://www.gravatar.com/avatar/2056d56888b443ab438fb956e898cc9d?s=300
  email    : email@ryey.icu
  linkedin : zhaoruigh
  github   : renyuneyun
  gitlab   : renyuneyun
  mastodon : "@renyuneyun"


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- vendor/
